openapi: 3.0.2
info:
  description: 'You can use this interface for trying out your Local REST API in Obsidian.


    Before trying the below tools, you will want to make sure you press the "Authorize" button below and provide the API Key you are shown when you open the "Local REST API" section of your Obsidian settings.  All requests to the API require a valid API Key; so you won''t get very far without doing that.


    When using this tool you may see browser security warnings due to your browser not trusting the self-signed certificate the plugin will generate on its first run.  If you do, you can make those errors disappear by adding the certificate as a "Trusted Certificate" in your browser or operating system''s settings.

    '
  title: Local REST API for Obsidian Active File Commands API
  version: '1.0'
servers:
- description: HTTPS (Secure Mode)
  url: https://{host}:{port}
  variables:
    host:
      default: 127.0.0.1
      description: Binding host
    port:
      default: '27124'
      description: HTTPS port
- description: HTTP (Insecure Mode)
  url: http://{host}:{port}
  variables:
    host:
      default: 127.0.0.1
      description: Binding host
    port:
      default: '27123'
      description: HTTP port
security:
- apiKeyAuth: []
tags:
- name: Commands
paths:
  /commands/:
    get:
      responses:
        '200':
          content:
            application/json:
              example:
                commands:
                - id: global-search:open
                  name: 'Search: Search in all files'
                - id: graph:open
                  name: 'Graph view: Open graph view'
              schema:
                properties:
                  commands:
                    items:
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                      type: object
                    type: array
                type: object
          description: A list of available commands.
      summary: 'Get a list of available commands.

        '
      tags:
      - Commands
  /commands/{commandId}/:
    post:
      parameters:
      - description: The id of the command to execute
        in: path
        name: commandId
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Success
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: The command you specified does not exist.
      summary: 'Execute a command.

        '
      tags:
      - Commands
components:
  schemas:
    Error:
      properties:
        errorCode:
          description: 'A 5-digit error code uniquely identifying this particular type of error.

            '
          example: 40149
          type: number
        message:
          description: Message describing the error.
          example: A brief description of the error.
          type: string
      type: object
  securitySchemes:
    apiKeyAuth:
      description: 'Find your API Key in your Obsidian settings

        in the "Local REST API" section under "Plugins".

        '
      scheme: bearer
      type: http
