openapi: 3.2.0
info:
  description: You can use this interface for trying out your Local REST API in Obsidian.
  title: Local REST API for Obsidian Open API
  version: '1.0'
servers:
- description: HTTPS (Secure Mode)
  url: https://{host}:{port}
  variables:
    host:
      default: 127.0.0.1
      description: Binding host
    port:
      default: '27124'
      description: HTTPS port
- description: HTTP (Insecure Mode)
  url: http://{host}:{port}
  variables:
    host:
      default: 127.0.0.1
      description: Binding host
    port:
      default: '27123'
      description: HTTP port
security:
- apiKeyAuth: []
tags:
- name: Open
paths:
  /open/{filename}:
    post:
      description: 'Note: Obsidian will create a new document at the path you have

        specified if such a document did not already exist.'
      parameters:
      - description: 'Path to the file to return (relative to your vault root).

          '
        in: path
        name: filename
        required: true
        schema:
          format: path
          type: string
      - description: Open this as a new leaf?
        in: query
        name: newLeaf
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Success
      summary: Open the specified document in the Obsidian user interface
      tags:
      - Open
      operationId: postOpenByFilename
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKeyAuth:
      description: 'Find your API Key in your Obsidian settings

        in the "Local REST API" section under "Plugins".

        '
      scheme: bearer
      type: http
